// constants/artEnums.js
const GENRES = [
  "Academic",
  "Abstract",
  "Abstract Expressionism",
  "African Traditional",
  "Allegorical",
  "American Scene Painting",
  "Ancient Egyptian",
  "Ancient Greek",
  "Ancient Roman",
  "Animal",
  "Andalusian",
  "Art Brut",
  "Art Nouveau",
  "Ashcan School",
  "Assemblage",
  "Bad Painting",
  "Bauhaus",
  "Bay Area Figurative",
  "Bio Art",
  "Botanical",
  "Byzantine",
  "Calligraphy",
  "Capriccio",
  "Caravaggisti",
  "Celtic",
  "Ceramic Art",
  "Chicago Imagists",
  "Chinese Literati",
  "Chinese Traditional",
  "Classical",
  "Cloisonnism",
  "Collage",
  "Color Field",
  "Community Art",
  "Conceptual Art",
  "Contemporary",
  "Context Art",
  "Conversation Piece",
  "Constructivism",
  "Contemporary",
  "Conversation Piece",
  "Contemporary",
  "Crypto Art",
  "Cubism",
  "Dada",
  "Decorative Arts",
  "Der Blaue Reiter",
  "Die Brücke",
  "Digital Art",
  "Divisionism",
  "Dutch Golden Age",
  "Earth Art",
  "Early Baroque",
  "Early Christian",
  "Early Netherlandish",
  "Early Renaissance",
  "Etruscan",
  "Etching",
  "Existentialist Art",
  "Expressionism",
  "Fauvism",
  "Feminist Art",
  "Flemish Baroque",
  "Florentine Renaissance",
  "Folk Art",
  "Four Gentlemen",
  "Fresco",
  "Futurism",
  "German Expressionism",
  "Genre Painting",
  "Genre Scene",
  "Glass Art",
  "Gothic",
  "Graffiti",
  "Graphic Design",
  "Group Portrait",
  "Gutai",
  "Hard-edge Painting",
  "Harlem Renaissance",
  "Hellenistic",
  "Historical",
  "Hudson River School",
  "Hyperrealism",
  "Iconoclastic",
  "Illuminated Manuscript",
  "Impressionism",
  "Indian Traditional",
  "Indonesian Traditional",
  "Installation Art",
  "Insular",
  "International Gothic",
  "Islamic Art",
  "Italian Renaissance",
  "Japanese Traditional",
  "Jewelry",
  "Japonism",
  "Kinetic Art",
  "Korean Traditional",
  "Lacquer",
  "Landscape",
  "Late Baroque",
  "Late Renaissance",
  "Luminism",
  "Magic Realism",
  "Mamluk",
  "Mannerism",
  "Marine",
  "Medieval",
  "Mesopotamian",
  "Metalwork",
  "Miniature",
  "Minimalism",
  "Mixed Media",
  "Modernism",
  "Monumental",
  "Moorish",
  "Mosaic",
  "Mughal",
  "Mythological",
  "Naive Art",
  "Naturalism",
  "Neoclassicism",
  "Neo-Expressionism",
  "Neo-Ge",
  "Neo-Impressionism",
  "Net Art",
  "New Leipzig School",
  "New Media Art",
  "NFT Art",
  "Nihonga",
  "Northern Renaissance",
  "Nude",
  "Oil Painting",
  "Op Art",
  "Orientalism",
  "Other",
  "Outsider Art",
  "Pastel",
  "Performance Art",
  "Persian",
  "Pictorial",
  "Pictures Generation",
  "Plein Air",
  "Pointillism",
  "Political Art",
  "Portrait",
  "Post-Impressionism",
  "Precisionism",
  "Pre-Columbian",
  "Prehistoric",
  "Pre-Raphaelite",
  "Pre-Romanesque",
  "Primitive Art",
  "Process Art",
  "Protest Art",
  "Public Art",
  "Renaissance",
  "Renaissance Classicism",
  "Relational Aesthetics",
  "Relief",
  "Religious",
  "Regionalism",
  "Realism",
  "Rococo",
  "Romanesque",
  "Romanticism",
  "Russian Avant-garde",
  "Salon",
  "Sculpture",
  "Self-Portrait",
  "Site-Specific",
  "Social Realism",
  "Spanish Golden Age",
  "Spiritual Art",
  "Stained Glass",
  "Still Life",
  "Street Art",
  "Stuckism",
  "Suprematism",
  "Surrealism",
  "Symbolism",
  "Tapestry",
  "Tenebrism",
  "Textile Art",
  "Thai Traditional",
  "Tibetan",
  "Tonalism",
  "Transavantgarde",
  "Tribal Art",
  "Typography",
  "Ukiyo-e",
  "Vanitas",
  "Veduta",
  "Venetian Renaissance",
  "Video Art",
  "Vienna Secession",
  "Wanderers",
  "Watercolor",
  "Woodcut",
  "World of Art",
  "Young British Artists",
  "Yoga"
];

const MEDIUMS = [
  "3D hologram fan",
  "3D printing filament",
  "Absorbent ground",
  "Acrylic",
  "Acrylic gouache",
  "Acrylic marker",
  "Acrylic panel",
  "Acrylic pouring medium",
  "Acrylic sheet",
  "Adhesive vinyl",
  "Airbrush",
  "Albumen print",
  "Algae-based paint",
  "Alginate",
  "Alkyd",
  "Amber",
  "Amate paper",
  "Animal hide",
  "Animal skull",
  "Annatto",
  "Antler",
  "Aquatint",
  "Ash",
  "Asphaltum",
  "Assemblage",
  "Baleen",
  "Banana paper",
  "Bamboo",
  "Bamboo charcoal",
  "Bamboo root",
  "Bandhani",
  "Batik",
  "Beach glass",
  "Beeswax",
  "Birch bark",
  "Birchbark",
  "Bioplastic",
  "Bitumen",
  "Blackened paper",
  "Block printing on fabric",
  "Blood",
  "Board",
  "Body paint",
  "Bobbin lace",
  "Bone",
  "Botanical",
  "Brass",
  "Bread",
  "Bristol board",
  "Bronze",
  "Buttons",
  "Calabash",
  "Calotype",
  "Canvas paper",
  "Capriccio",
  "Cardboard",
  "Casein",
  "Casein tempera",
  "Cactus juice",
  "Carbon fiber",
  "Carbon print",
  "Cave walls",
  "Ceramic",
  "Ceramic art",
  "Ceramic glaze",
  "Ceramic tile",
  "Chalk",
  "Chalk painting",
  "Charcoal",
  "Charcoal from specific trees",
  "Cherry gum",
  "Chipboard",
  "Chinese Literati",
  "Chromatic clay",
  "Cinnabar",
  "Circuit board",
  "Clay mixed with saliva",
  "Clear gesso",
  "Cloisonnism",
  "Cochineal",
  "Coffee",
  "Collage",
  "Collagraph",
  "Collodion process",
  "Colored smoke",
  "Concrete",
  "Conté crayon",
  "Conversation Piece",
  "Copper",
  "Copper leaf",
  "Copper mesh",
  "Copper plate",
  "Copper plate engraving",
  "Cornstarch clay",
  "Cotton",
  "Cotton canvas",
  "Cowrie shells",
  "Crayon",
  "Crewelwork",
  "Crushed ants",
  "Crypto Art",
  "Cyanotype",
  "Daguerreotype",
  "Decorative Arts",
  "Dendrite",
  "Der Blaue Reiter",
  "Die Brücke",
  "Digital",
  "Digital Art",
  "Digital brush",
  "Digital painting",
  "Digital print",
  "Digital screen",
  "Digital vinyl",
  "Divisionism",
  "Dragon's blood",
  "Driftwood",
  "Drypoint",
  "Dye",
  "Earth pigment",
  "Egg shell mosaic",
  "Egg tempera",
  "Electroformed copper",
  "Electroplating",
  "Embroidery",
  "Emulsion",
  "Enamel paint",
  "Encaustic",
  "Encaustic stick",
  "Engobe",
  "Engraving",
  "Epoxy",
  "Etching",
  "Existentialist Art",
  "Expanded polystyrene",
  "Fabric paint",
  "Fabric scraps",
  "Fauvism",
  "Feathers",
  "Felt-making",
  "Fiber optic art",
  "Fig milk",
  "Fire",
  "Fish glue",
  "Fish scales",
  "Flake white",
  "Flowers",
  "Foam board",
  "Folk Art",
  "Found object",
  "Four Gentlemen",
  "Fresco",
  "Fresco secco",
  "Fruit juices",
  "Futurism",
  "Gamboge",
  "Gall ink",
  "Gesso panels",
  "Glass",
  "Glass Art",
  "Glass microsphere",
  "Glass paint",
  "Glass plate",
  "Glair",
  "Glow stick",
  "Gold",
  "Gold leaf",
  "Goldwork embroidery",
  "Gongbi",
  "Gourds",
  "Graphic Design",
  "Graphite",
  "Graphite powder",
  "Group Portrait",
  "Ground medium",
  "Gum arabic",
  "Gum bichromate",
  "Gutai",
  "Hair",
  "Hand-stretched canvas",
  "Handmade paper",
  "Hard pastel",
  "Hardboard",
  "Henna",
  "Holographic film",
  "Holography",
  "Horn",
  "House paint",
  "Hyperrealism",
  "Ikat",
  "Illuminated Manuscript",
  "Impressionism",
  "Indigo",
  "Ink",
  "Installation Art",
  "Interactive touch paint",
  "International Gothic",
  "Iron",
  "Iridescent pigment",
  "Ivory",
  "Jade",
  "Jewelry",
  "Jute",
  "Jute canvas",
  "Kalamkari",
  "Kente cloth",
  "Keys",
  "Kermes",
  "Kinetic Art",
  "Lacquer",
  "Latex paint",
  "Lapis lazuli",
  "Leather",
  "Leaves",
  "LED art",
  "LED mesh",
  "LED tape",
  "Letterpress ink",
  "Limestone",
  "Linocut",
  "Lithographic crayon",
  "Lithography",
  "Logwood",
  "Lokta paper",
  "Lowbrow",
  "Luminism",
  "Madder root",
  "Magic Realism",
  "Magnetic paint",
  "Mahogany panel",
  "Mamluk",
  "Map",
  "Marker",
  "Marble",
  "Marble dust gesso",
  "Marine",
  "Masonite",
  "Masonry",
  "Medieval",
  "Mezzotint",
  "Metal",
  "Metal leaf",
  "Metalpoint",
  "Mineral pigment",
  "Miniature",
  "Mirror",
  "Mixed media",
  "Mosaic",
  "Mosaic tile",
  "Mother of pearl",
  "Mother-of-pearl inlay",
  "Mud",
  "Mud cloth",
  "Mud resist",
  "Mulberry bark",
  "Mulberry paper",
  "Mural paint",
  "Naive Art",
  "Naturalism",
  "Needle lace",
  "Neoclassicism",
  "Neo-Geo",
  "Newsprint",
  "Nihonga",
  "Nude",
  "Oak panel",
  "Obsidian",
  "Ochre",
  "Oil on canvas",
  "Oil on oak panel",
  "Oil on wood",
  "Oil pastel",
  "Oil Painting",
  "Oil stick",
  "Old maps",
  "Op Art",
  "Orpiment",
  "Other",
  "Outsider Art",
  "Palladium leaf",
  "Papier-mâché",
  "Papyrus",
  "Parchment",
  "Pastel",
  "Pastel pencil",
  "Pearlescent pigment",
  "Performance Art",
  "Persian",
  "Persimmon juice",
  "Photographic emulsion on glass",
  "Photographic paper",
  "Photomontage",
  "Photography",
  "Pigment",
  "Pigment stick",
  "Pine needles",
  "Pine panel",
  "Pitch",
  "Plant dye",
  "Plant juice",
  "Plantain leaves",
  "Plaster",
  "Plaster wall",
  "Platinum",
  "Platinum print",
  "Plastic",
  "Plein Air",
  "Pointillism",
  "Political Art",
  "Poplar panel",
  "Portrait",
  "Pottery",
  "Pottery glaze",
  "Powdered glass",
  "Pre-stretched canvas",
  "Prepared clay tablets",
  "Pressed flowers",
  "Primitive Art",
  "Printer's ink",
  "Print",
  "Process Art",
  "Protest Art",
  "Public Art",
  "Puffy paint",
  "Pyrography",
  "QR code art",
  "Quilting",
  "Rabbit skin glue",
  "Raffia",
  "Realgar",
  "Realism",
  "Reflective beads",
  "Relational Aesthetics",
  "Relief",
  "Relief etching",
  "Relief media",
  "Resin",
  "Resin with embedded pigment",
  "Resin-coated canvas",
  "Reverse glass",
  "Rice paper",
  "Rice paste",
  "Rice straw paper",
  "Rococo",
  "Romanticism",
  "Rosin powder",
  "Rusted metals",
  "Rust",
  "Sanded pastel paper",
  "Sand",
  "Sand painting",
  "Sandstone",
  "Sap green",
  "Sculpture",
  "Screen printing ink",
  "Screenprint",
  "Self-Portrait",
  "Sepia",
  "Sepia ink",
  "Serpentine",
  "Sgraffito layer",
  "Shell",
  "Shell gold",
  "Shellac",
  "Shellac-based ink",
  "Sheet music",
  "Shibori",
  "Silk",
  "Silkscreen ink",
  "Silver",
  "Silver leaf",
  "Silverpoint",
  "Site-Specific",
  "Sized canvas",
  "Slate",
  "Slip",
  "Smoke",
  "Smoke-fired ceramic",
  "Soft pastel",
  "Soft-ground etching",
  "Solar cell",
  "Spices",
  "Spray dye",
  "Spray foam",
  "Spray paint",
  "Stained Glass",
  "Stamp",
  "Steel",
  "Steel engraving",
  "Steel wool",
  "Stone",
  "Stone dust",
  "Stone wall",
  "Stuckism",
  "Sugar",
  "Sumi ink",
  "Suprematism",
  "Sweetgrass",
  "Symbolism",
  "Syrrup",
  "Synthetic polymer",
  "Synthetic resin",
  "Tagua nut",
  "Tapestry",
  "Tar",
  "Tea staining",
  "Tempera",
  "Tempera and oil on plaster",
  "Tempera grassa",
  "Tempera on gesso",
  "Tempera on canvas",
  "Textile",
  "Textile Art",
  "Therapeutic Art",
  "Thermochromic paint",
  "Tibetan",
  "Tie-dye",
  "Tile",
  "Tinfoil",
  "Titanium",
  "Titanium white",
  "Tonalism",
  "Toned paper",
  "Tortoiseshell",
  "Tree sap mediums",
  "Tribal Art",
  "Tragacanth gum",
  "Trompe-l",
  "Turmeric",
  "Tusche",
  "UV-reactive paint",
  "Vanitas",
  "Veduta",
  "Vegetable dye",
  "Velum",
  "Vienna Secession",
  "Vintage photographs",
  "Vinyl paint",
  "Vinyl wrap",
  "Viscosity printing",
  "Wall",
  "Wanderers",
  "Watercolor",
  "Watercolor paper",
  "Wax",
  "Wet-plate collodion",
  "Whalebone",
  "Weld",
  "Wine",
  "Wool",
  "Wood",
  "Wood engraving",
  "Wood panel",
  "Woodblock printing",
  "Woodcut",
  "World of Art",
  "Yolk tempera variations",
  "Young British Artists",
  "Zinc",
  "Zinc white"
];


const CURRENCIES = [
  'USD', 'EUR', 'GBP', 'LKR', 'INR', 'JPY', 'CNY', 'CHF', 'AUD', 'Other'
];

module.exports = { GENRES, MEDIUMS, CURRENCIES };
